alias drop='cd ~/Dropbox\ \(The\ University\ of\ Manchester\)/'
alias train='cd ~/Dropbox\ \(The\ University\ of\ Manchester\)/rit-training'
alias course='cd ~/Dropbox\ \(The\ University\ of\ Manchester\)/rit-training/course-material'
alias csf2='ssh -X mbexegc2@csf2.itservices.manchester.ac.uk'
alias csf3='ssh -X mbexegc2@csf3.itservices.manchester.ac.uk'
