alias csf3='ssh -X mbexegc2@csf3.itservices.manchester.ac.uk'
alias csf4='ssh -X mbexegc2@csf4.itservices.manchester.ac.uk'
alias restart_gp='sudo systemctl restart gpd'
alias icsf='ssh -X mbexegc2@incline256.itservices.manchester.ac.uk'
alias teaching='PS1="$ ";PROMPT_COMMAND=""'
alias makefile_dag='make -Bnd | make2graph | dot -Tpng -o makefile_DAG.png'
alias dirac='ssh -X dc-cape1@login8.cosma.dur.ac.uk'
alias csfslurm='ssh -X mbexegc2@login01-csf3-test.itservices.manchester.ac.uk'
